apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpc
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: uxp-lab
  source:
    path: /lab-argocd/aws-examples/vpc
    repoURL: https://github.com/upbound/uxp-training
    targetRevision: HEAD
