apiVersion: azure.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release.sh
spec:
  id: platform-ref-azure
  parameters:
    nodes:
      count: 1 #1-100
      size: small #small/medium/large
    services:
      operators:
        prometheus:
          version: "15.0.1"
  writeConnectionSecretToRef:
    name: platform-ref-azure-kubeconfig #Must be unique for each instance
