apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmariadbinstances.azure.platformref.upbound.io
  labels:
    dbengine: mariadb
    provider: azure
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: azure.platformref.upbound.io/v1alpha1
    kind: XSQLInstance
  resources:
    - name: mariadlserver
      base:
        apiVersion: dbformariadb.azure.upbound.io/v1beta1
        kind: Server
        spec:
          forProvider:
            version: "10.3"
            administratorLogin: xp-admin
            location: West US 2
            skuName: GP_Gen5_2
            storageMb: 5120
            sslEnforcementEnabled: false
            sslMinimalTlsVersionEnforced: TLSEnforcementDisabled
            identity:
            - type: SystemAssigned
      patches:
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-mariadb"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
          - type: string
            string:
              fmt: "%s-mariadb"
        - fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.storageMb
          transforms:
          - type: math
            math:
              multiply: 1024
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/network-id]
        - fromFieldPath: spec.parameters.passwordSecretRef.namespace
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.namespace
        - fromFieldPath: spec.parameters.passwordSecretRef.name
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
        - fromFieldPath: spec.parameters.passwordSecretRef.key
          toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.key
      connectionDetails:
        - type: FromFieldPath
          name: host
          fromFieldPath: status.atProvider.fqdn
        - type: FromConnectionSecretKey
          name: # Fill me in
          fromConnectionSecretKey: username
        - type: FromConnectionSecretKey
          name: # Fill me in
          fromConnectionSecretKey: password
        - type: FromConnectionSecretKey
          name: # Fill me in
          # Add "port" field form "port" field of the connection secret
    # db-server vnet-rule for subnet where AKS lives in
    - name: vnetrule
      base:
        apiVersion: dbformariadb.azure.upbound.io/v1beta1
        kind: VirtualNetworkRule
        spec:
          forProvider:
            serverNameSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-sn-rule"
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[azure.platformref.upbound.io/network-id]
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/network-id]
    - name: database
      base:
        apiVersion: dbformariadb.azure.upbound.io/v1beta1
        kind: Database
        spec:
          forProvider:
            charset: utf8
            collation: utf8_general_ci
            serverNameSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: metadata.name
          transforms:
            - type: match
              match:
                patterns:
                  - type: regexp
                    regexp: '.*'
                    result: upbound
        - fromFieldPath: spec.parameters.clusterRef.id
          toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/network-id]
