apiVersion: azure.platformref.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-azure-ghost
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-release-app.sh
spec:
  providerConfigRef:
    name: platform-ref-azure
  passwordSecretRef:
    namespace: default
    name: platform-ref-azure-db-conn-mariadb
  writeConnectionSecretToRef:
    name: platform-ref-azure-app-conn
