apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:

  name: xnetworks.aws.platformref.upbound.io

  labels:
    # An optional convention is to include a label of the XRD. This allows
    # easy discovery of compatible Compositions.

    crossplane.io/xrd: xnetworks.platformref.upbound.io

    # The following label marks this Composition for AWS. This label can
    # be used in 'compositionSelector' in an XR or Claim.
    provider: aws

    # Other labels can be added to match.
spec:

  # Each Composition must declare that it is compatible with a particular type
  # of Composite Resource using its 'compositeTypeRef' field. The referenced
  # version must be marked 'referenceable' in the XRD that defines the XR.

  # Multiple Compositions can refer to the same Composite Resource.
  compositeTypeRef:
     apiVersion: aws.platformref.upbound.io/v1alpha1
     kind: XNetwork

  # When an XR is created in response to a claim Crossplane needs to know where
  # it should create the XR's connection secret. This is configured using the
  # 'writeConnectionSecretsToNamespace' field.

  # Upbound's UXP usually uses the  upbound-system namespace.
  # CNCF Crossplane is installed to the crossplane-system namespace.
  writeConnectionSecretsToNamespace: upbound-system

  # Each Composition must specify at least one composed resource template. In
  # this case the Composition tells Crossplane that it should create, update, or
  # delete a VPC whenever someone creates, updates, or deletes an
  # XNetwork

  # The next section is a list of resources that is part of the composition.
  # We'll be filling these in during the next labs.

  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPC
