apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: getting-started-with-aws
  annotations:
    uxp-guide: getting-started
spec:
  crossplane:
    version: ">=v1.2.1"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws
      version: "v0.8.0"
